<?php

namespace NahidFerdous\LaravelModuleGenerator\Providers;

use Illuminate\Support\ServiceProvider;
use NahidFerdous\LaravelModuleGenerator\Console\Commands\GenerateModuleFromModelName;
use NahidFerdous\LaravelModuleGenerator\Console\Commands\GenerateModuleFromYaml;
use NahidFerdous\LaravelModuleGenerator\Console\Commands\GeneratePostmanCollection;
use NahidFerdous\LaravelModuleGenerator\Console\Commands\GenerateDbDiagram;

class LaravelModuleGeneratorServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->mergeConfigFrom(__DIR__.'/../config/module-generator.php', 'module-generator');
    }

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                GenerateModuleFromModelName::class,
                GenerateModuleFromYaml::class,
                GeneratePostmanCollection::class,
                GenerateDbDiagram::class,
            ]);

            // Publish stubs separately
            $this->publishes([
                __DIR__.'/../../stubs' => base_path('generate-module/stubs'),
            ], 'module-generator-stubs');

            // Publish config separately
            $this->publishes([
                __DIR__.'/../../config/module-generator.php' => config_path('module-generator.php'),
            ], 'module-generator-config');

            // Publish both together with general tag
//            $this->publishes([
//                __DIR__.'/../../stubs' => base_path('generate-module/stubs'),
//                __DIR__.'/../../config/module-generator.php' => config_path('module-generator.php'),
//            ], 'module-generator');

            // Publish stubs and config
            $this->publishes([
                __DIR__.'/stub' => base_path('generate-module/stub'),
                __DIR__.'/../config/config.php' => config_path('module-generator.php'),
            ], 'module-generator');

            // ✅ Auto-create models.yaml if not exists
            $this->ensureModelsYamlExists();
        }
    }

    protected function ensureModelsYamlExists(): void
    {
        $path = config('module-generator.models_path');
        $directory = dirname($path); // get the directory portion of the path

        if (! file_exists($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $directory));
        }

        if (! file_exists($path)) {
            file_put_contents($path, <<<'YAML'
# This file is auto-generated by LaravelModuleGenerator
# Define your models here. Example:

# User:
#   fields:
#     name: string
#     email: string
#     password: string
YAML
            );
        }
    }
}
