<?php

namespace NahidFerdous\LaravelModuleGenerator\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Support\Facades\File;
use Symfony\Component\Yaml\Yaml;

class Install extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    // protected $signature = 'module-generator:install';
    protected $signature = 'module-generator:install {--force : Overwrite existing files without confirmation}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Install the Laravel Module Generator package and optionally generate the Auth Module';

    protected $basePath;

    /**
     * Execute the console command.
     *
     * @return int
     *
     * @throws \JsonException
     */
    public function handle()
    {
        $this->basePath = base_path();

        // ✅ Auto-create models.yaml if not exists
        $this->ensureModelsYamlExists();
        $this->copyDefaultFiles();
        $this->updateBootstrapApp();
        $this->updateComposerJson();

        //        $authConfirm = $this->ask('Would you like to generate the Auth Module with login, register, forget-password, reset-password, profile? (yes/no)', 'no');
        //        if (strtolower($authConfirm) === 'yes') {
        //            $this->call('module:generate-auth');
        //        } else {
        //            $this->info('Skipped generating Auth Module.');
        //        }
        //
        //        $rolesAndPermissionsConfirm = $this->ask('Would you like to generate the Roles and Permissions Module with Spatie laravel-permission? (yes/no)', 'no');
        //        if (strtolower($rolesAndPermissionsConfirm) === 'yes') {
        //            $this->call('module:generate-roles');
        //        } else {
        //            $this->info('Skipped generating Auth Module.');
        //        }
    }

    protected function copyDefaultFiles(): void
    {
        $this->info('Generating Traits...');

        $files = [
            'Traits/MetaResponseTrait' => 'app/Traits/MetaResponseTrait.php',
            'Traits/ApiResponseTrait' => 'app/Traits/ApiResponseTrait.php',
            'Traits/HandlesPagination' => 'app/Traits/HandlesPagination.php',
            'Traits/HasSlugModelBinding' => 'app/Traits/HasSlugModelBinding.php',
            'Traits/HasSlug/HasSlug' => 'app/Traits/HasSlug/HasSlug.php',
            'Traits/HasSlug/SlugOptions' => 'app/Traits/HasSlug/SlugOptions.php',
            'Traits/HasSlug/Exceptions/InvalidOption' => 'app/Traits/HasSlug/Exceptions/InvalidOption.php',

            'Exceptions/ExceptionHandler' => 'app/Exceptions/ExceptionHandler.php',

            'Helpers/FileManager' => 'app/Helpers/FileManager.php',
            'Helpers/GeneralHelper' => 'app/Helpers/GeneralHelper.php',
        ];

        $this->copyFiles($files, __DIR__.'/../../_stubs');
        $this->copyFiles([
            'Middleware/Cors' => 'app/Http/Middleware/Cors.php',
            'Middleware/Authenticate' => 'app/Http/Middleware/Authenticate.php',
            'resources/views/errors/error.blade' => 'resources/views/errors/error.blade.php',
        ], __DIR__.'/../../_stubs/AuthModule');
    }

    protected function ensureModelsYamlExists(): void
    {
        $path = config('module-generator.models_path');
        $directory = dirname($path); // get the directory portion of the path

        if (! file_exists($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $directory));
        }

        if (! file_exists($path)) {
            file_put_contents($path, <<<'YAML'
# This file is auto-generated by LaravelModuleGenerator
# Define your models here. Example:

User:
  generate_only: seeder
  fields:
    name: string
    email: string:unique
    email_verified_at: dateTime:nullable
    password: string
    avatar: image:nullable
    status: boolean:default true
    last_login_at: timestamp:nullable

Category:
  generate_except: seeder
  fields:
    name: string:unique
    slug: string:unique
    description: text:nullable
    image: image:nullable
    parent_id: foreignId:categories:nullable
    is_active: boolean:default true
    display_order: integer:default 0
    seo_title: string:nullable
    seo_description: string:nullable
    seo_keywords: string:nullable
    created_by: foreignId:users:nullable
    updated_by: foreignId:users:nullable
  relations:
    belongsTo: Category:parent, User:creator, User:updater
    hasMany: Category:children, Product:products
  nested_requests: children

Product:
  generate_except: seeder
  fields:
    vendor_id: foreignId:vendors:nullable
    category_id: foreignId:categories
    brand_id: foreignId:brands:nullable
    name: string
    slug: string:unique
    sku: string:unique
    description: text:nullable
    short_description: string:nullable
    price: double:default 0
    cost_price: double:default 0
    compare_price: double:default 0
    quantity: integer:default 0
    is_active: boolean:default true
    is_featured: boolean:default false
    rating: double:default 0
    total_reviews: integer:default 0
    weight: double:nullable
    dimensions: string:nullable
    seo_title: string:nullable
    seo_description: string:nullable
    seo_keywords: string:nullable
    meta_data: json:nullable
    created_by: foreignId:users:nullable
    updated_by: foreignId:users:nullable
    deleted_at: dateTime:nullable
  relations:
    belongsTo: Vendor, Category, Brand, User:creator, User:updater
    hasMany: Review, ProductVariant:variants, ProductImage:images
    belongsToMany: ProductAttribute
  nested_requests: variants, images

ProductImage:
  generate_except: seeder
  fields:
    product_id: foreignId:products
    image_url: image
    alt_text: string:nullable
    display_order: integer:default 0
    is_thumbnail: boolean:default false
    created_by: foreignId:users:nullable
    updated_by: foreignId:users:nullable
  relations:
    belongsTo: Product, User:creator, User:updater

ProductVariant:
  generate_except: seeder
  fields:
    product_id: foreignId:products
    sku: string:unique
    name: string
    price: double:nullable
    cost_price: double:nullable
    quantity: integer:default 0
    attributes_data: json:nullable
    image_id: foreignId:product_images:nullable
    is_active: boolean:default true
    created_by: foreignId:users:nullable
    updated_by: foreignId:users:nullable
  relations:
    belongsTo: Product, ProductImage:image, User:creator, User:updater

ProductAttributeValue:
  generate_except: seeder
  fields:
    attribute_id: foreignId:product_attributes
    value: string
    slug: string
    display_order: integer:default 0
    created_by: foreignId:users:nullable
    updated_by: foreignId:users:nullable
  relations:
    belongsTo: ProductAttribute:attribute, User:creator, User:updater
  unique:
    - [product_attribute_id, value]


YAML
            );
        }
    }

    protected function copyFiles(array $files, string $path): void
    {
        foreach ($files as $source => $destination) {
            // Determine source extension based on file type
            $sourceExtension = '.stub';

            // For blade files, the stub should have .blade.stub extension
            if (str_ends_with($destination, '.blade.php')) {
                $sourcePath = $path.'/'.$source.'.stub';
            } else {
                $sourcePath = $path.'/'.$source.'.stub';
            }

            $destinationPath = $this->basePath.'/'.$destination;

            if (! File::exists($sourcePath)) {
                $this->warn("⚠️  Source file not found: {$sourcePath}");

                continue;
            }

            if (File::exists($destinationPath) && ! $this->option('force')) {
                if (! $this->confirm("File already exists: {$destination}. Do you want to replace it?", false)) {
                    $this->line("⏭️  Skipped: {$destination}");

                    continue;
                }
            }

            $directory = dirname($destinationPath);
            if (! File::isDirectory($directory)) {
                File::makeDirectory($directory, 0755, true);
            }

            File::copy($sourcePath, $destinationPath);
            $this->line("✅ Created: {$destination}");
        }
    }

    protected function updateBootstrapApp(): void
    {
        $bootstrapPath = base_path('bootstrap/app.php');

        if (! File::exists($bootstrapPath)) {
            $this->warn('⚠️  bootstrap/app.php not found');

            return;
        }

        $this->info('📝 Updating bootstrap/app.php...');

        $content = File::get($bootstrapPath);
        $modified = false;

        // Handle withMiddleware section
        if (preg_match('/->withMiddleware\(function\s*\(Middleware\s+\$middleware\)\s*:\s*void\s*\{(.*?)\}\)/s', $content, $matches)) {
            $middlewareContent = $matches[1];
            $updatedMiddlewareContent = $middlewareContent; // Start with existing content

            // Check if alias method exists
            if (! str_contains($middlewareContent, '$middleware->alias(')) {
                // Build the alias array
                $aliases = "\n        \$middleware->alias([\n";
                $aliases .= "            'auth' => \\App\\Http\\Middleware\\Authenticate::class,\n";
                $aliases .= "            'cors' => \\App\\Http\\Middleware\\Cors::class,\n";
                $aliases .= '        ]);';
                $updatedMiddlewareContent .= $aliases;
                $modified = true;
                $this->line('✅ Added middleware aliases');
            } else {
                // If alias exists, check and add individual aliases
                if (! str_contains($middlewareContent, "'cors'")) {
                    $updatedMiddlewareContent = preg_replace(
                        '/(\$middleware->alias\(\[\s*\n)/s',
                        "$1            'cors' => \\App\\Http\\Middleware\\Cors::class,\n",
                        $updatedMiddlewareContent
                    );
                    $modified = true;
                    $this->line('✅ Added cors middleware alias');
                }
                if (! str_contains($middlewareContent, "'auth'")) {
                    $updatedMiddlewareContent = preg_replace(
                        '/(\$middleware->alias\(\[\s*\n)/s',
                        "$1            'auth' => \\App\\Http\\Middleware\\Authenticate::class,\n",
                        $updatedMiddlewareContent
                    );
                    $modified = true;
                    $this->line('✅ Added auth middleware alias');
                }
            }

            // Replace the middleware content
            $content = preg_replace(
                '/->withMiddleware\(function\s*\(Middleware\s+\$middleware\)\s*:\s*void\s*\{.*?\}\)/s',
                "->withMiddleware(function (Middleware \$middleware): void {{$updatedMiddlewareContent}\n    })",
                $content
            );
        }

        // Handle withExceptions section
        if (preg_match('/->withExceptions\(function\s*\(Exceptions\s+\$exceptions\)\s*:\s*void\s*\{(.*?)\}\)/s', $content, $matches)) {
            $exceptionsContent = $matches[1];

            // Check if an exception handler already exists
            if (! str_contains($exceptionsContent, 'ExceptionHandler::handle')) {
                $updatedExceptionsContent = "\n        \\App\\Exceptions\\ExceptionHandler::handle(\$exceptions);";

                $content = preg_replace(
                    '/->withExceptions\(function\s*\(Exceptions\s+\$exceptions\)\s*:\s*void\s*\{.*?\}\)/s',
                    "->withExceptions(function (Exceptions \$exceptions): void {{$updatedExceptionsContent}\n    })",
                    $content
                );
                $modified = true;
                $this->line('✅ Added exception handler');
            }
        }

        if ($modified) {
            File::put($bootstrapPath, $content);
            $this->info('✅ bootstrap/app.php updated successfully');
        } else {
            $this->line('ℹ️  bootstrap/app.php already up to date');
        }
    }

    /**
     * Update composer.json to autoload helper files
     *
     * @throws FileNotFoundException
     * @throws \JsonException
     */
    protected function updateComposerJson(): void
    {
        $this->info('📝 Updating composer.json to autoload helpers...');

        $composerJsonPath = base_path('composer.json');

        if (! File::exists($composerJsonPath)) {
            $this->warn('⚠️  composer.json not found');

            return;
        }

        $composerJson = json_decode(File::get($composerJsonPath), true, 512, JSON_THROW_ON_ERROR);
        $modified = false;

        // Initialize autoload.files array if it doesn't exist
        if (! isset($composerJson['autoload']['files'])) {
            $composerJson['autoload']['files'] = [];
        }

        // Helper files to add
        $helperFiles = [
            'app/Helpers/GeneralHelper.php',
            'app/Helpers/FileManager.php',
        ];

        // Add helper files if they don't already exist
        foreach ($helperFiles as $file) {
            if (! in_array($file, $composerJson['autoload']['files'], true)) {
                $composerJson['autoload']['files'][] = $file;
                $modified = true;
                $this->line("✅ Added {$file} to autoload files");
            } else {
                $this->line("ℹ️  {$file} already in autoload files");
            }
        }

        if ($modified) {
            // Write back to composer.json with pretty print
            File::put(
                $composerJsonPath,
                json_encode($composerJson, JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n"
            );
            $this->info('✅ composer.json updated successfully');

            // Run composer dump-autoload
            $this->info('Running composer dump-autoload...');
            exec('composer dump-autoload 2>&1', $output, $returnCode);

            if ($returnCode === 0) {
                $this->info('✅ Autoload files regenerated');
            } else {
                $this->warn('⚠️  Failed to run composer dump-autoload automatically');
                $this->warn('Please run manually: composer dump-autoload');
            }
        } else {
            $this->line('ℹ️  composer.json already up to date');
        }
    }
}
