<?php

namespace NahidFerdous\LaravelModuleGenerator\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Yaml\Yaml;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Symfony\Component\Console\Exception\CommandNotFoundException;

class Install extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'module-generator:install';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Install the Laravel Module Generator package and optionally generate the Auth Module';

    protected $basePath;

    /**
     * Execute the console command.
     *
     * @return int
     * @throws \JsonException
     */
    public function handle()
    {
        $this->basePath = base_path();

        // ✅ Auto-create models.yaml if not exists
        $this->ensureModelsYamlExists();
        $this->copyDefaultFiles();
        $this->updateBootstrapApp();
        $this->updateComposerJson();

        //        $authConfirm = $this->ask('Would you like to generate the Auth Module with login, register, forget-password, reset-password, profile? (yes/no)', 'no');
        //        if (strtolower($authConfirm) === 'yes') {
        //            $this->call('module:generate-auth');
        //        } else {
        //            $this->info('Skipped generating Auth Module.');
        //        }
        //
        //        $rolesAndPermissionsConfirm = $this->ask('Would you like to generate the Roles and Permissions Module with Spatie laravel-permission? (yes/no)', 'no');
        //        if (strtolower($rolesAndPermissionsConfirm) === 'yes') {
        //            $this->call('module:generate-roles');
        //        } else {
        //            $this->info('Skipped generating Auth Module.');
        //        }
    }

    protected function copyDefaultFiles(): void
    {
        $this->info('Generating Traits...');

        $files = [

            'Traits/MetaResponseTrait' => 'app/Traits/MetaResponseTrait.php',
            'Traits/ApiResponseTrait' => 'app/Traits/ApiResponseTrait.php',
            'Traits/HandlesPagination' => 'app/Traits/HandlesPagination.php',
            'Traits/HasSlugModelBinding' => 'app/Traits/HasSlugModelBinding.php',
            'Traits/HasSlug/HasSlug' => 'app/Traits/HasSlug/HasSlug.php',
            'Traits/HasSlug/SlugOptions' => 'app/Traits/HasSlug/SlugOptions.php',
            'Traits/HasSlug/Exceptions/InvalidOption' => 'app/Traits/HasSlug/Exceptions/InvalidOption.php',

            'Exceptions/ExceptionHandler' => 'app/Exceptions/ExceptionHandler.php',

            'Helpers/FileManager' => 'app/Helpers/FileManager.php',
            'Helpers/GeneralHelper' => 'app/Helpers/GeneralHelper.php',
        ];

        $this->copyFiles($files, __DIR__ . '/../../_stubs');
        $this->copyFiles([
            'Middleware/Cors' => 'app/Http/Middleware/Cors.php',
            'Middleware/Authenticate' => 'app/Http/Middleware/Authenticate.php',
            'resources/views/errors/error.blade' => 'resources/views/errors/error.blade.php',
        ], __DIR__ . '/../../AuthModule');
    }

    protected function ensureModelsYamlExists(): void
    {
        $path = config('module-generator.models_path');
        $directory = dirname($path); // get the directory portion of the path

        if (!file_exists($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $directory));
        }

        if (!file_exists($path)) {
            file_put_contents($path, <<<'YAML'
# This file is auto-generated by LaravelModuleGenerator
# Define your models here. Example:

User:
  generate:
    model: false
    migration: false
    controller: false
    service: false
    request: false
    resource: false
    collection: false
  fields:
    name: string
    username: string:nullable
    email: string:unique
    email_verified_at: dateTime:nullable
    password: string

YAML
            );
        }
    }

    protected function copyFiles(array $files, string $path): void
    {
        foreach ($files as $source => $destination) {
            // Determine source extension based on file type
            $sourceExtension = '.stub';

            // For blade files, the stub should have .blade.stub extension
            if (str_ends_with($destination, '.blade.php')) {
                $sourcePath = $path . '/' . $source . '.stub';
            } else {
                $sourcePath = $path . '/' . $source . '.stub';
            }

            $destinationPath = $this->basePath . '/' . $destination;

            if (!File::exists($sourcePath)) {
                $this->warn("⚠️  Source file not found: {$sourcePath}");

                continue;
            }

            if (File::exists($destinationPath) && !$this->option('force')) {
                if (!$this->confirm("File already exists: {$destination}. Do you want to replace it?", false)) {
                    $this->line("⏭️  Skipped: {$destination}");

                    continue;
                }
            }

            $directory = dirname($destinationPath);
            if (!File::isDirectory($directory)) {
                File::makeDirectory($directory, 0755, true);
            }

            File::copy($sourcePath, $destinationPath);
            $this->line("✅ Created: {$destination}");
        }
    }


    protected function updateBootstrapApp(): void
    {
        $bootstrapPath = base_path('bootstrap/app.php');

        if (!File::exists($bootstrapPath)) {
            $this->warn('⚠️  bootstrap/app.php not found');

            return;
        }

        $this->info('📝 Updating bootstrap/app.php...');

        $content = File::get($bootstrapPath);
        $modified = false;

        // Handle withMiddleware section
        if (preg_match('/->withMiddleware\(function\s*\(Middleware\s+\$middleware\)\s*:\s*void\s*\{(.*?)\}\)/s', $content, $matches)) {
            $middlewareContent = $matches[1];
            $updatedMiddlewareContent = $middlewareContent;

            // Add statefulApi if not exists
            if (!str_contains($middlewareContent, '$middleware->statefulApi()')) {
                $updatedMiddlewareContent = "\n        \$middleware->statefulApi();";
                $modified = true;
                $this->line('✅ Added statefulApi middleware');
            }

            // Check if alias method exists
            if (!str_contains($middlewareContent, '$middleware->alias(')) {
                // Build the alias array
                $aliases = "\n        \$middleware->alias([\n";
                $aliases .= "            'auth' => \App\Http\Middleware\Authenticate::class,";
                $aliases .= "            'cors' => App\Http\Middleware\Cors::class,\n";

                $aliases .= '        ]);';
                $updatedMiddlewareContent .= $aliases;
                $modified = true;
                $this->line('✅ Added middleware aliases');
            } else {
                if (!str_contains($middlewareContent, "'cors'")) {
                    $updatedMiddlewareContent = preg_replace(
                        '/(\$middleware->alias\(\[)/s',
                        "$1\n            'cors' => App\Http\Middleware\Cors::class,",
                        $updatedMiddlewareContent
                    );
                    $modified = true;
                }
                if (!str_contains($middlewareContent, "'auth'")) {
                    $updatedMiddlewareContent = preg_replace(
                        '/(\$middleware->alias\(\[)/s',
                        "$1\n            'auth' => \App\Http\Middleware\Authenticate::class,",
                        $updatedMiddlewareContent
                    );
                    $modified = true;
                }
            }

            // Replace the middleware content
            $content = preg_replace(
                '/->withMiddleware\(function\s*\(Middleware\s+\$middleware\)\s*:\s*void\s*\{.*?\}\)/s',
                "->withMiddleware(function (Middleware \$middleware): void {{$updatedMiddlewareContent}\n    })",
                $content
            );
        }

        // Handle withExceptions section
        if (preg_match('/->withExceptions\(function\s*\(Exceptions\s+\$exceptions\)\s*:\s*void\s*\{(.*?)\}\)/s', $content, $matches)) {
            $exceptionsContent = $matches[1];

            // Check if an exception handler already exists
            if (!str_contains($exceptionsContent, 'ExceptionHandler::handle')) {
                $updatedExceptionsContent = "\n        App\Exceptions\ExceptionHandler::handle(\$exceptions);";

                $content = preg_replace(
                    '/->withExceptions\(function\s*\(Exceptions\s+\$exceptions\)\s*:\s*void\s*\{.*?\}\)/s',
                    "->withExceptions(function (Exceptions \$exceptions): void {{$updatedExceptionsContent}\n    })",
                    $content
                );
                $modified = true;
                $this->line('✅ Added exception handler');
            }
        }

        if ($modified) {
            File::put($bootstrapPath, $content);
            $this->info('✅ bootstrap/app.php updated successfully');
        } else {
            $this->line('ℹ️  bootstrap/app.php already up to date');
        }
    }


    /**
     * Update composer.json to autoload helper files
     *
     * @throws FileNotFoundException
     * @throws \JsonException
     */
    protected function updateComposerJson(): void
    {
        $this->info('📝 Updating composer.json to autoload helpers...');

        $composerJsonPath = base_path('composer.json');

        if (!File::exists($composerJsonPath)) {
            $this->warn('⚠️  composer.json not found');
            return;
        }

        $composerJson = json_decode(File::get($composerJsonPath), true, 512, JSON_THROW_ON_ERROR);
        $modified = false;

        // Initialize autoload.files array if it doesn't exist
        if (!isset($composerJson['autoload']['files'])) {
            $composerJson['autoload']['files'] = [];
        }

        // Helper files to add
        $helperFiles = [
            'app/Helpers/GeneralHelper.php',
            'app/Helpers/FileManager.php',
        ];

        // Add helper files if they don't already exist
        foreach ($helperFiles as $file) {
            if (!in_array($file, $composerJson['autoload']['files'], true)) {
                $composerJson['autoload']['files'][] = $file;
                $modified = true;
                $this->line("✅ Added {$file} to autoload files");
            } else {
                $this->line("ℹ️  {$file} already in autoload files");
            }
        }

        if ($modified) {
            // Write back to composer.json with pretty print
            File::put(
                $composerJsonPath,
                json_encode($composerJson, JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n"
            );
            $this->info('✅ composer.json updated successfully');

            // Run composer dump-autoload
            $this->info('Running composer dump-autoload...');
            exec('composer dump-autoload 2>&1', $output, $returnCode);

            if ($returnCode === 0) {
                $this->info('✅ Autoload files regenerated');
            } else {
                $this->warn('⚠️  Failed to run composer dump-autoload automatically');
                $this->warn('Please run manually: composer dump-autoload');
            }
        } else {
            $this->line('ℹ️  composer.json already up to date');
        }
    }
}
